name: K6 Performance Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup K6
        uses: grafana/setup-k6-action@v1.1.0
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1.1.3
        with:
          path: src/tests

  # Exportar e mostrar as métricas de desempenho no console
      - name: Display K6 Test Metrics
        run: |
          k6 run src/tests/test.js --summary-export=summary.json --out json=k6_output.json
          cat k6_output.json | jq '.'  # Exibir as